// Auto-generated by scripts/generate-bundles.js — do not edit by hand.

import type { Base64Image } from './_types'

import * as image_v2_1 from './backgrounds/image_v2_1.ts'
import * as image_v2_10 from './backgrounds/image_v2_10.ts'
import * as image_v2_11 from './backgrounds/image_v2_11.ts'
import * as image_v2_12 from './backgrounds/image_v2_12.ts'
import * as image_v2_13 from './backgrounds/image_v2_13.ts'
import * as image_v2_14 from './backgrounds/image_v2_14.ts'
import * as image_v2_15 from './backgrounds/image_v2_15.ts'
import * as image_v2_16 from './backgrounds/image_v2_16.ts'
import * as image_v2_2 from './backgrounds/image_v2_2.ts'
import * as image_v2_3 from './backgrounds/image_v2_3.ts'
import * as image_v2_4 from './backgrounds/image_v2_4.ts'
import * as image_v2_5 from './backgrounds/image_v2_5.ts'
import * as image_v2_6 from './backgrounds/image_v2_6.ts'
import * as image_v2_7 from './backgrounds/image_v2_7.ts'
import * as image_v2_8 from './backgrounds/image_v2_8.ts'
import * as image_v2_9 from './backgrounds/image_v2_9.ts'
import * as thumb_1 from './backgrounds/thumb_1.ts'
import * as thumb_2 from './backgrounds/thumb_2.ts'
import * as thumb_3 from './backgrounds/thumb_3.ts'
import * as thumb_4 from './backgrounds/thumb_4.ts'
import * as thumb_5 from './backgrounds/thumb_5.ts'

export const builtInBackgroundModules: ReadonlyArray<Base64Image> = [
  { mime: image_v2_1.mime, data: image_v2_1.data },
  { mime: image_v2_10.mime, data: image_v2_10.data },
  { mime: image_v2_11.mime, data: image_v2_11.data },
  { mime: image_v2_12.mime, data: image_v2_12.data },
  { mime: image_v2_13.mime, data: image_v2_13.data },
  { mime: image_v2_14.mime, data: image_v2_14.data },
  { mime: image_v2_15.mime, data: image_v2_15.data },
  { mime: image_v2_16.mime, data: image_v2_16.data },
  { mime: image_v2_2.mime, data: image_v2_2.data },
  { mime: image_v2_3.mime, data: image_v2_3.data },
  { mime: image_v2_4.mime, data: image_v2_4.data },
  { mime: image_v2_5.mime, data: image_v2_5.data },
  { mime: image_v2_6.mime, data: image_v2_6.data },
  { mime: image_v2_7.mime, data: image_v2_7.data },
  { mime: image_v2_8.mime, data: image_v2_8.data },
  { mime: image_v2_9.mime, data: image_v2_9.data },
  { mime: thumb_1.mime, data: thumb_1.data },
  { mime: thumb_2.mime, data: thumb_2.data },
  { mime: thumb_3.mime, data: thumb_3.data },
  { mime: thumb_4.mime, data: thumb_4.data },
  { mime: thumb_5.mime, data: thumb_5.data },
]
