// Auto-generated by scripts/generate-bundles.js — do not edit by hand.

import type { Base64Image } from './_types'

import * as mask_1 from './tiles/1-mask.ts'
import * as shadow_1 from './tiles/1-shadow.ts'
import * as overlay_1 from './tiles/1-overlay.ts'
import * as mask_2 from './tiles/2-mask.ts'
import * as shadow_2 from './tiles/2-shadow.ts'
import * as overlay_2 from './tiles/2-overlay.ts'
import * as mask_3 from './tiles/3-mask.ts'
import * as shadow_3 from './tiles/3-shadow.ts'
import * as overlay_3 from './tiles/3-overlay.ts'
import * as mask_4 from './tiles/4-mask.ts'
import * as shadow_4 from './tiles/4-shadow.ts'
import * as overlay_4 from './tiles/4-overlay.ts'

export const builtInGraphModules: ReadonlyArray<{
  mask: Base64Image
  shadow: Base64Image
  overlay: Base64Image
}> = [
  { mask: mask_1, shadow: shadow_1, overlay: overlay_1 },
  { mask: mask_2, shadow: shadow_2, overlay: overlay_2 },
  { mask: mask_3, shadow: shadow_3, overlay: overlay_3 },
  { mask: mask_4, shadow: shadow_4, overlay: overlay_4 },
]
